### ISSUE TITLE
missing $openssl param

### ISSUE THREAD

**Issue by bwalex** [xaque208/puppet-openvpn#24]
Commit 57639867f379ad334e4a4da4d3f67a7f3f513aca removed the $openssl param, but it's still referenced in manifests/server.pp.

**Comment by xaque208** [comment]
Ah, so it is.  Could you send a PR for this?  Apologies for the trouble.

**Comment by xaque208** [comment]
@bwalex Any interest in sending a PR for this?

**Comment by xaque208** [comment]
I believe this has been resolved.
