### ISSUE TITLE
Should test on Puppet4

### ISSUE THREAD

**Issue by xaque208** [xaque208/puppet-openvpn#30]
There is at least one error I know of when running this module in a Puppet4 environment.  Testing should be updated to ensure compatibility.

**Comment by trefzer** [comment]
Just for Info: I'm running puppet 4, pull requests #38 and #39 are a result of migrating from 3 to 4 !

**Comment by xaque208** [comment]
Excellent @trefzer.  I've not been using this module lately, but I'm likely going to start.  I'd like to adopt more of the native puppet4 approaches to this module as well.  Type validation, and the hiera data in modules specifically come to mind.  The params bits you worked on would get a whole lot simpler if it was just data.
