### ISSUE TITLE
Service not started correctly on Ubuntu Xenial

### ISSUE THREAD

**Issue by insertjokehere** [xaque208/puppet-openvpn#35]
On Ubuntu Xenial, starting the `openvpn` service is not sufficient to connect a client, the SystemD unit `openvpn@<connection name>` needs to be started, where connection name is the name of the `.conf` file in `/etc/openvpn`

**Comment by xaque208** [comment]
Thank you for the report.  Would you be able to provide patches to support this?  I suspect systemd updates for Ubuntu will benefit other platforms that also use systemd.

**Comment by insertjokehere** [comment]
Yep, I've got a workaround that I'm using at the moment, will try to wrap it up into a patch in the next few days
