### ISSUE TITLE
allow override of config file name

### ISSUE THREAD

**Issue by neoice** [xaque208/puppet-openvpn#42]
https://github.com/xaque208/puppet-openvpn/blob/master/manifests/client.pp#L27

`  file { "${openvpn_dir}/${server}.conf":`

sane default good, sane default with configurable parameter even better :)

**Comment by xaque208** [comment]
You can set the hiera data for `openvpn::openvpn_dir` to set that value, or declare an openvpn class like so.

``` Puppet
class { 'openvpn': openvpn_dir => '/somewhere/else' }
```

The default data for that value is at https://github.com/xaque208/puppet-openvpn/tree/master/data
