### ISSUE TITLE
new Forge release?

### ISSUE THREAD

**Issue by neoice** [xaque208/puppet-openvpn#48]
https://forge.puppet.com/zleslie/openvpn points to this repo as it's "Project URL".

> Version 1.1.5 released Apr 4th 2016

you appear to have cut a few releases since then:

![image](https://user-images.githubusercontent.com/71924/50116059-f4631a80-01fd-11e9-8974-becd3c40939e.png)

are you planning on releasing to Forge? I prefer the simpler experience of this module over https://forge.puppet.com/puppet/openvpn

**Comment by xaque208** [comment]
2.0.2 has been uploaded.  I'll try to work a forge release into my process here out.
